DROP TABLE PERSON;
DROP TABLE JOB;
DROP SEQUENCE PERSON_PNO_SQ;   
    
CREATE TABLE JOB(
    jNO NUMBER(2) PRIMARY KEY,
    jNAME VARCHAR2(30) NOT NULL UNIQUE
);

CREATE TABLE PERSON (
    pNO NUMBER(5) PRIMARY KEY,
    pNAME VARCHAR2(30) NOT NULL,
    jNO NUMBER(2),
    KOR NUMBER(3) CHECK(KOR>=0 AND KOR<=100),
    ENG NUMBER(3) CHECK(ENG>=0 AND ENG<=100),
    MAT NUMBER(3) CHECK(MAT>=0 AND MAT<=100),
    FOREIGN KEY(jNO) REFERENCES JOB(jNO)
);

SELECT * FROM JOB;
SELECT * FROM PERSON;

INSERT INTO JOB 
    VALUES (10, '배우');
INSERT INTO JOB 
    VALUES (20, '가수');
INSERT INTO JOB 
    VALUES (30, '엠씨');
    
INSERT INTO PERSON
    VALUES (PERSON_PNO_SQ.NEXTVAL, '정우성', 10, 90, 80, 81);
INSERT INTO PERSON
    VALUES (PERSON_PNO_SQ.NEXTVAL, '박세영', 10, 80, 90, 80);    
INSERT INTO PERSON
    VALUES (PERSON_PNO_SQ.NEXTVAL, '배수지', 20, 20, 90, 90);    
    
COMMIT;

CREATE SEQUENCE PERSON_PNO_SQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;
    
COMMIT;

DROP SEQUENCE PERSON_PNO_SQ;