-- [VIII] 8장 Sequence : 순차번호 생성기 / 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE FRIEND_SEQ
    START WITH 1 -- 1부터 시작함 (기본값)
    INCREMENT BY 1 -- 1씩 증가함 (기본값)
    MAXVALUE 9999 -- 최대값
    MINVALUE 1 -- 최소값
    NOCACHE
    NOCYCLE;

SELECT FRIEND_SEQ.NEXTVAL -- 다음 순차번호 생성
    FROM DUAL;
    
SELECT FRIEND_SEQ.CURRVAL -- 시퀀스의 현재 값 임둥
    FROM DUAL;
    
-- FRIEND테이블(NO-PK, NAME, TEL, ADDDRESS, LAST_MODIFY)
DROP SEQUENCE FRIEND_SEQ;

CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
    
DROP TABLE FRIEND;

CREATE TABLE FRIEND(
    NO NUMBER(11) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(20) UNIQUE,
    ADDDRESS VARCHAR2(255),
    LAST_MODIFY DATE DEFAULT SYSDATE
);
SELECT TO_CHAR(SYSDATE, 'YYYYMMDD')||TRIM(TO_CHAR(1, '000'))
    FROM DUAL;
INSERT INTO FRIEND (NO, NAME, TEL, ADDDRESS)
    VALUES (TO_CHAR(SYSDATE, 'YYYYMMDD')||
        TRIM(TO_CHAR(FRIEND_SEQ.NEXTVAL, '000')), '홍길동', NULL, '서울시 관악구');
SELECT * FROM FRIEND;

DROP TABLE MEMBER;
DROP TABLE MEMBER_LEVEL;
DROP SEQUENCE MEMBER_SEQ;

CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;

CREATE TABLE MEMBER_LEVEL (
    LEVELNO VARCHAR2(10) PRIMARY KEY,
    LEVELNAME VARCHAR2(30) NOT NULL UNIQUE
);   

SELECT * FROM MEMBER_LEVEL;

CREATE TABLE MEMBER (
    mNO NUMBER(5),
    mNAME VARCHAR2(12) NOT NULL,
    mPW VARCHAR2(8) NOT NULL CHECK(LENGTH(mPW) BETWEEN 1 AND 8),
    mEMAIL VARCHAR2(30) UNIQUE,
    mPOINT NUMBER(10) NOT NULL CHECK(mPOINT >= 0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO VARCHAR2(10),
    PRIMARY KEY(mNO),
    FOREIGN KEY(LEVELNO) REFERENCES MEMBER_LEVEL(LEVELNO)    
);

SELECT * FROM MEMBER;

INSERT INTO MEMBER_LEVEL (LEVELNO, LEVELNAME)
    VALUES ('-1', 'BLACK');
INSERT INTO MEMBER_LEVEL
    VALUES ('0', '일반');
INSERT INTO MEMBER_LEVEL
   VALUES ('1', '실버');   
INSERT INTO MEMBER_LEVEL
    VALUES ('2', '골드');

INSERT INTO MEMBER
    VALUES (MEMBER_SEQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, TO_DATE('22/03/10', 'RR/MM/DD'), 0);
INSERT INTO MEMBER 
    VALUES (MEMBER_SEQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, TO_DATE('22/04/01', 'RR/MM/DD'), 1);

SELECT * FROM MEMBER;

SELECT mNO "가입순서", mNAME "성함", mRDATE "가입일", mEMAIL "이메일", mPOINT POINT, LEVELNAME || '고객' "고객 등급"
    FROM MEMBER M, MEMBER_LEVEL L
    WHERE M.LEVELNO = L.LEVELNO;






























