-- 친구 데이터 저장할 TABLE,시퀀스,더미데이터 생성
DROP TABLE FRIEND;
DROP SEQUENCE FRIEND_NO_SQ;

CREATE TABLE FRIEND(
    NO NUMBER(4) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    TEL VARCHAR2(30) UNIQUE
);

CREATE SEQUENCE FRIEND_NO_SQ MAXVALUE 9999 NOCACHE;


INSERT INTO FRIEND
    VALUES (FRIEND_NO_SQ.NEXTVAL, '홍길동', '010-1234-5678');
INSERT INTO FRIEND
    VALUES (FRIEND_NO_SQ.NEXTVAL, '김길동', '010-4234-5678');
INSERT INTO FRIEND
    VALUES (FRIEND_NO_SQ.NEXTVAL, '박길동', '010-1224-5618');
INSERT INTO FRIEND
    VALUES (FRIEND_NO_SQ.NEXTVAL, '박길동', NULL);
-- DAO에 들어갈 QUERY 작성
INSERT INTO FRIEND
    VALUES (FRIEND_NO_SQ.NEXTVAL, '신길동', '010-1234-5678');

SELECT * FROM FRIEND;    
COMMIT;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    